version: "3.9"
networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:

  postgres_users:
    image: postgres:15.3
    container_name: who_users_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=who_users_db
    volumes:
      - postgres_users:/data/postgres_users
      - ./create_who_users_db.sql:/docker-entrypoint-initdb.d/create_who_users_db.sql
    restart: always

  postgres_user:
    image: postgres:15.3
    container_name: user_db
    ports:
      - "5480:5480"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./created_user_db.sql:/docker-entrypoint-initdb.d/create_user_db.sql
    networks:
      - postgres_user
    restart: always

  postgres_message:
    image: postgres:15.3
    container_name: who_message_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=who_message_db
    volumes:
      - postgres_message:/data/postgres_message
      - ./create_who_message_db.sql:/docker-entrypoint-initdb.d/create_who_message_db.sql
    restart: always

  discovery-service:
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway-service:
    container_name: gateway-service
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8222:8222"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-service
      - zipkin

  users-service:
    container_name: users-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres_users
      - discovery-service
      - gateway-service
      - zipkin

  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - users-service
      - gateway-service

  keycloak:
    image: jboss/keycloak:16.1.1
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  postgres_users:
  postgres_message:
  pgdata: