version: "3.9"
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  postgres_users:
    image: postgres:15.3
    container_name: who_users_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=who_users_db
    volumes:
      - postgres_users:/data/postgres_users
      - ./create_who_users_db.sql:/docker-entrypoint-initdb.d/create_who_users_db.sql
    restart: always

  postgres_message:
    image: postgres:15.3
    container_name: who_message_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=who_message_db
    volumes:
      - postgres_message:/data/postgres_message
      - ./create_who_message_db.sql:/docker-entrypoint-initdb.d/create_who_message_db.sql
    restart: always

  discovery-service:
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway-service:
    container_name: gateway-service
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8222:8222"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-service
      - zipkin


#  user-service:
#    container_name: users-service
#    build:
#      context: ./users-service
#      dockerfile: Dockerfile
#    ports:
#      - "8070:8070"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - discovery-service
#      - gateway-service
#      - zipkin



volumes:
  postgres_users:
  postgres_message: