eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/who_message_db
    username: admin
    password: root
  rabbitmq:
    host: 127.0.0.1
    port: 15672
    username: admin
    password: root

