eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: message-service

  profiles:
    active: dev

  cloud:
    config:
      enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true


  flyway:
    locations: classpath:db/migration

server:
  port: 8070

management:
  tracing:
    sampling:
      probability: 1.0
