eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://message_db:5432/who_message_db
    username: admin
    password: root


management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
