eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

#spring:
#  cloud:
#    gateway:
#      routes:
#        - id:
#          uri:
#          predicates:


management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
