eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://127.0.0.1:8070
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthenticationFilter
        - id: message-service
          uri: http://127.0.0.1:8071
          predicates:
            - Path=/api/v1/message/**
          filters:
            - AuthenticationFilter
        - id: auth-service
            uri: http://127.0.0.1:8010
            predicates:
              - Path=/api/v1/auth/**

