spring:
  application:
    name: gateway-service

  cloud:
    config:
      enabled: false

  profiles:
    active: dev

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8222

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

