eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8070
          predicates:
            - Path=/api/v1/user/**
        - id: message-service
          uri: http://message-service:8071
          predicates:
            - Path=/api/v1/message/**


management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
