eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #      defaultZone: http://discovery-service:8761/eureka
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:instead
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/deafphone_db
    username: postgres
    password: root

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 7550

management:
  tracing:
    sampling:
      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans
